language: c++
sudo: required
os:
- linux
- osx
dist: trusty
osx_image: xcode7.3
env:
  global:
  - BUILD_NUMBER=${TRAVIS_BUILD_NUMBER}
  - VERSION=3.12.2.${TRAVIS_BUILD_NUMBER}
  - secure: vX847To3osqI7JytpiH5r6xlXS9r8KCNCPP3pu2yvGxAgmz917xG1lrqRGOReoCe/08hkh+gMA9vLjIyUwDlUvZuKJr5g5iPfa85/m9iPe24DLOlf9zLI5It0MFNTLYFQ5DXFmX77+/lcB9ypDQtE5w9XK+xZjyC9xr9viye77E=

before_install:
- git submodule update --init --recursive && if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
    sudo ln -s /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-migrator/sdk/MacOSX.sdk/usr/include/openssl /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include;
    brew update;
    brew install qt5;
    curl --location "https://github.com/open-eid/libdigidoc/releases/download/v3.10.2/libdigidoc_3.10.1.1213.pkg" -o libdigidoc.pkg;
    curl --location "https://github.com/open-eid/libdigidocpp/releases/download/v3.12.2/libdigidocpp_3.12.2.1329.pkg" -o libdigidocpp.pkg;
    curl --location "https://github.com/open-eid/esteid-pkcs11/releases/download/v3.10.1/esteid-pkcs11_3.10.1.64.pkg" -o esteid-pkcs11.pkg;
    sudo installer -verboseR -pkg libdigidoc.pkg -target /;
    sudo installer -verboseR -pkg libdigidocpp.pkg -target /;
    sudo installer -verboseR -pkg esteid-pkcs11.pkg -target /;
  else
    curl https://installer.id.ee/media/sources/public.key | sudo apt-key add -;
    sudo apt-add-repository 'deb http://installer.id.ee/media/ubuntu/ trusty main';
    sudo apt-get update -qq;
    sudo apt-get install -y libdigidocpp-dev libldap2-dev libpcsclite-dev libssl-dev qtbase5-dev qttools5-dev qttools5-dev-tools gettext dh-make devscripts dpkg-dev cdbs;
  fi
script: if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
    mkdir build && cd build && cmake -DQt5_DIR=/usr/local/opt/qt5/lib/cmake/Qt5 -DOPENSSL_ROOT_DIR=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr ..;
    make zipdebug macdeployqt zip && cd ..;
  else
    yes | dh_make --createorig --addmissing --defaultless -p qdigidoc_${VERSION};
    dch --distribution $(lsb_release -cs) -v ${VERSION} "Release ${VERSION}.";
    dpkg-buildpackage -rfakeroot -us -uc;
  fi

addons:
  coverity_scan:
    project:
      name: open-eid/qdigidoc
      description: Build submitted via Travis CI
    notification_email: raul@metsma.ee
    build_command_prepend: mkdir coverity; cd coverity; cmake -DBREAKPAD='' ..
    build_command: make
    branch_pattern: coverity_scan

before_deploy:
- export VERSION=${TRAVIS_TAG:1}
- git clean -d -x -f
- cd ..
- mv qdigidoc qdigidoc-${VERSION}
- tar czf qdigidoc-${VERSION}.tar.gz --exclude-vcs qdigidoc-${VERSION}
deploy:
  provider: releases
  api_key:
    secure: LS4Q49BiN1OCs0LMFf8jACtFWnqHEgIP2k+Y7/YWhzp/KBZ8U+45z2EA37NbmYM2GFYCcXLApyKZYWCHq42vz5LQYKLk9/08RU60Xo6jnNUwBhnc0MTj1JzSfMITaWqwJ7LCvJZa1QJnA2/rQuYtVxakzQF9OGxHEmZH0Nujce4=
  file: qdigidoc-${VERSION}.tar.gz
  skip_cleanup: true
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"
