before_install:
- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
    brew update;
    brew install qt5;
  else
    sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
    sudo add-apt-repository -y ppa:beineri/opt-qt521;
    sudo add-apt-repository -y ppa:ria-id/travis;
    sudo apt-get update -qq;
    sudo apt-get install -y gcc-4.8 g++-4.8 qt52base qt52tools libpcsclite-dev libxml-security-c-dev libssl-dev libc6-i386;
    sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90;
    source /opt/qt52/bin/qt52-env.sh;
    wget http://ftp.id.eesti.ee/pub/id/libdigidocpp/libdigidocpp-common_3.10.0.4114.BETA-1410_all.deb;
    wget http://ftp.id.eesti.ee/pub/id/libdigidocpp/libdigidocpp-dev_3.10.0.4114.BETA-1410_amd64.deb;
    wget http://ftp.id.eesti.ee/pub/id/libdigidocpp/libdigidocpp0_3.10.0.4114.BETA-1410_amd64.deb;
    sudo dpkg -i libdigidocpp-common_3.10.0.4114.BETA-1410_all.deb libdigidocpp0_3.10.0.4114.BETA-1410_amd64.deb libdigidocpp-dev_3.10.0.4114.BETA-1410_amd64.deb;
    wget http://www.cmake.org/files/v3.0/cmake-3.0.2-Linux-i386.tar.gz;
    tar -xzf cmake-3.0.2-Linux-i386.tar.gz;
    sudo cp -fR cmake-3.0.2-Linux-i386/* /usr;
  fi
script:
- mkdir build
- cd build
- cmake -DBREAKPAD="" ..
- make

os:
 - linux
 - osx

env:
  global:
   - secure: "vX847To3osqI7JytpiH5r6xlXS9r8KCNCPP3pu2yvGxAgmz917xG1lrqRGOReoCe/08hkh+gMA9vLjIyUwDlUvZuKJr5g5iPfa85/m9iPe24DLOlf9zLI5It0MFNTLYFQ5DXFmX77+/lcB9ypDQtE5w9XK+xZjyC9xr9viye77E="

addons:
  coverity_scan:
    project:
      name: "open-eid/qdigidoc"
      description: "Build submitted via Travis CI"
    notification_email: raul@metsma.ee
    build_command_prepend: "mkdir coverity; cd coverity; cmake -DBREAKPAD='' .."
    build_command: make
    branch_pattern: coverity_scan
