sudo: required
services:
 - docker
before_install:
- if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
    brew update;
    brew install qt5;
  else
    curl https://installer.id.ee/media/sources/public.key | sudo apt-key add -;
    sudo apt-add-repository 'deb http://installer.id.ee/media/ubuntu/ trusty main';
    sudo apt-get update -qq;
    sudo apt-get install -y libdigidocpp-dev libldap2-dev libpcsclite-dev libssl-dev qtbase5-dev qttools5-dev qttools5-dev-tools gettext;
  fi
script:
- mkdir build
- cd build
- cmake -DBREAKPAD="" ..
- make

os:
 - linux

env:
  global:
   - secure: "vX847To3osqI7JytpiH5r6xlXS9r8KCNCPP3pu2yvGxAgmz917xG1lrqRGOReoCe/08hkh+gMA9vLjIyUwDlUvZuKJr5g5iPfa85/m9iPe24DLOlf9zLI5It0MFNTLYFQ5DXFmX77+/lcB9ypDQtE5w9XK+xZjyC9xr9viye77E="

addons:
  coverity_scan:
    project:
      name: "open-eid/qdigidoc"
      description: "Build submitted via Travis CI"
    notification_email: raul@metsma.ee
    build_command_prepend: "mkdir coverity; cd coverity; cmake -DBREAKPAD='' .."
    build_command: make
    branch_pattern: coverity_scan
